### ISSUE TITLE
The call to sequencer came too early

### ISSUE THREAD

**Issue by MGronse** [zkparty/trusted-setup-frontend#145]
I get this error when I try to contribute to the ceremony

**Comment by NicoSerranoP** [comment]
Hey! What browser and wallet provider are you using? :)

**Comment by MGronse** [comment]
Google Chrome, Metamask
Wallet address, if it can help 0x5B26c872bCdaB99AFd6dcf073803640a930D142d 
Sometimes my wait is just interrupted with the error "Unknown user. Please log in again with a different account"

**Comment by NicoSerranoP** [comment]
@MGronse there is a known issue with the sequencer that should be resolved soon (check the [PR](https://github.com/ethereum/kzg-ceremony-sequencer/pull/176) here). This would prevent the kick out of the ceremony lobby ("Unknown user. Please log in again with a different account").

"The call to sequencer came too early" might be related to your internet connection. Could you retry using another internet connection? Remember that the lobby is packed right now but there is still plenty of time to contribute (2 months from now)

**Comment by glamperd** [comment]
I saw a `call to sequencer came too early` error. It seems to revert to normal `try_contribute` calls straight away, although the UI still shows the message, instead of restoring the normal lobby page.
